name: push configuration to infra

on:
  push:
    paths: ["public/**"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: setup aws CLI
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: copy file to s3
        run: aws s3 cp public s3://cmcloudlab520.info --recursive
